In [3]:
import pandas as pd

bank = pd.read_csv('word_bank.csv')

bank

         word
0           a
1     ability
2        able
3       about
4       above
..        ...
995       yet
996       you
997     young
998      your
999  yourself

[1000 rows x 1 columns]

In [4]:
bank = bank[bank['word'].str.len() >= 3]

bank

         word
1     ability
2        able
3       about
4       above
5      accept
..        ...
995       yet
996       you
997     young
998      your
999  yourself

[972 rows x 1 columns]

In [13]:
def isInWordBank(word):
    words = bank[bank['word'].str.upper() == word.upper()]
    return len(words) > 0

def test(word):
    print(f'{word} is {'NOT ' if not isInWordBank(word) else ''}in the word bank')

In [ ]:
for word in ['fly', 'spoon', 'burger', 'a', 'i', 'as', 'few', 'american']:
    test(word)

fly is in the word bank
spoon is NOT in the word bank
burger is NOT in the word bank
a is NOT in the word bank
i is NOT in the word bank
as is NOT in the word bank
few is in the word bank
american is in the word bank